### ISSUE TITLE
Error: Unknown primitive "[object Object]" at traverse

### ISSUE THREAD

**Issue by braco** [pateketrueke/json-schema-faker#4]
```
Error: Unknown primitive "[object Object]" at traverse
```
Any idea what would cause this error?

Also, key paths would be super handy in debugging. For example, this coffeescript code produces key paths like "foo.bar.baz" from an object:
```
isObject = (obj) -> Object.prototype.toString.call(obj) is '[object Object]'
allProperties = (object, path=[]) ->
  props = []
  for key, val of object
    here = path.concat([key])
    props.push here.join(".")
    if isObject val
      props.push allProperties(val, here)...
  props
```
Error messages could thus be "Error in foo.bar.baz: ...." so it was clear what was breaking.

**Comment by braco** [comment]
Seems to be caused by something in links.items.type here (CSON notation):

```
    links:
      description: "..."
      type: "array"
      items:
        type: "object"
```
