### ISSUE TITLE
properties: type: type: 'string' throws error

### ISSUE THREAD

**Issue by braco** [pateketrueke/json-schema-faker#5]
```
{
type: 'object'
properties:
  relationship:
    type: 'string'
  type:
    type: 'string'
  title:
    type: 'string'
}
```

"properties.type" is causing 'unknown primitive {"type":"string"}'.

(Thanks for the error reporting update)
